package cn.suishoucms.weixin.sun.mapper;

import org.apache.ibatis.annotations.Param;
import cn.suishoucms.weixin.sun.entity.Session;

public interface SessionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int insert(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int insertSelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    Session selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Session record);

    Session selectBy(@Param("sessionId") String sessionId, @Param("key") String key);

    int del(@Param("sessionId") String sessionId, @Param("key") String key);
}
