package cn.suishoucms.weixin.sun.mapper;

import java.util.List;
import cn.suishoucms.weixin.sun.entity.StoreUser;

public interface StoreUserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int insert(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int insertSelective(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    StoreUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreUser record);

    List<StoreUser> selectOwnerStoreUser(Integer userId);
}
