package cn.suishoucms.weixin.sun.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table session
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Session {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   服务器sessionId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.session_id
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * Database Column Remarks:
     *   键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * Database Column Remarks:
     *   值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * Database Column Remarks:
     *   插入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.id
     *
     * @return the value of session.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.id
     *
     * @param id the value for session.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.session_id
     *
     * @return the value of session.session_id
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.session_id
     *
     * @param sessionId the value for session.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.key
     *
     * @return the value of session.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.key
     *
     * @param key the value for session.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.value
     *
     * @return the value of session.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.value
     *
     * @param value the value for session.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.insert_time
     *
     * @return the value of session.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.insert_time
     *
     * @param insertTime the value for session.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.update_time
     *
     * @return the value of session.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.update_time
     *
     * @param updateTime the value for session.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
