---
- hosts: "{{hosts}}"
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: "create the tmp directory!"
      shell: mkdir "{{tomcathome}}/tmp"
      ignore_errors: True
      
    - name: backup
      shell: mv {{tomcathome}}/tmp/{{finalName}}.war {{tomcathome}}/tmp/{{finalName}}bak.war
      ignore_errors: True
            
    - name: copy war to tmp
      copy: src={{ war_path }} dest={{tomcathome}}/tmp/
      
          
    - name: offline
      shell: rm {{tomcathome}}/webapps/ROOT/index.html
      ignore_errors: True
      
    - name: pause 30s
      pause: seconds=30
      
    - name: stop tomcat
      shell: ps -ef | grep {{tomcathome}} | grep -v grep | awk '{print $2}' | xargs kill -9
      ignore_errors: True
       
    - name: rm
      shell: rm {{tomcathome}}/webapps/{{finalName}}.war
      ignore_errors: True
      
    - name: rm -rf
      shell: rm -rf {{tomcathome}}/webapps/{{finalName}}
      ignore_errors: True
    - name: copy war to tmp
      shell: cp {{tomcathome}}/tmp/{{finalName}}.war  {{tomcathome}}/webapps/{{finalName}}.war
        
    - name: start tomcat
      shell: export LANG=en_US.UTF-8 && nohup {{tomcathome}}/bin/startup.sh

      
    - name: pause 30s
      pause: seconds=30
      
    - name: wait for tomcat to start
      wait_for: port=80 timeout=30      
      
    - name: online
      shell: echo "" >{{tomcathome}}/webapps/ROOT/index.html      
  
                                 